### ISSUE TITLE
Remove error about missing startup videos from log

### ISSUE THREAD

**Issue by CamoRF** [rfg-modding/RSL2#8]
- Disable `Int3 critical function at C:/unit4projects/rfg/root/code/volition/rfg/code/interface/ui_startup_video.cpp(214)` in the built in log when you remove startup videos from `startup_video_sequence.xtbl`

**Comment by Moneyl** [comment]
Does this show up still with the last version or RSL2 I sent you? I removed one of the video errors but may have missed this one.

**Comment by CamoRF** [comment]
Yeah it does


![Image](https://user-images.githubusercontent.com/113881920/235273374-ad9ba63f-441f-4bd0-bf74-b649389a8668.png)

**Comment by CamoRF** [comment]
This issue can be closed, if you blank out the entire `.xtbl` the game doesn't care.
